steps:
  # 1. Create new Pub/Sub topic
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["pubsub", "topics", "create", "github-topic"]

  # 2. Deploy cloud function A that will publish messages to the new topic
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "github-func-a"
      - "--runtime=python310"
      - "--trigger-http"
      - "--entry-point=start_script"
      - "--region=europe-west3"
      - "--no-allow-unauthenticated"
      - "--max-instances=1"
      - "--timeout=120s"
      - "--memory=256MiB"
      - "--ingress-settings=all"
      - "--gen2"
      - "--service-account=sa-func-a@propane-nomad-396712.iam.gserviceaccount.com"
      - "--source=./code/publisher"

  # 3. Deploy cloud function B that will subscribe to the new topic
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "github-func-b"
      - "--runtime=python310"
      - "--trigger-topic=my-topic"
      - "--entry-point=start_script"
      - "--region=europe-west3"
      - "--no-allow-unauthenticated"
      - "--max-instances=1"
      - "--timeout=120s"
      - "--memory=256MiB"
      - "--ingress-settings=all"
      - "--gen2"
      - "--service-account=sa-func-b@propane-nomad-396712.iam.gserviceaccount.com"
      - "--source=./code/subscriber"

  # 4. Deploy a cloud scheduler that will trigger cloud function A on a daily basis
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "scheduler"
      - "jobs"
      - "create"
      - "http"
      - "github-func-a-scheduler"
      - "--schedule=0 4 * * *"
      - "--http-method=POST"
      - "--uri=https://europe-west3-propane-nomad-396712.cloudfunctions.net/github-func-a"
      - '--message-body={"project_id": "propane-nomad-396712", "my_msg": "Hello World!"}'
      - "--headers=Content-Type=application/json"
      - "--attempt-deadline=1800s"
      - "--oidc-service-account-email=cloud-scheduler@propane-nomad-396712.iam.gserviceaccount.com"
      - "--location=europe-west3"

# Define the affected branches
substitutions:
  _BRANCH: ".*" # Match all branches by default

# Trigger only on pushes that modify files other than the README
trigger:
  branch: $_BRANCH
  event: push
  files:
    - "**/*.*"
  excludedFiles:
    - "**/README.*"
