steps:
  # 1. Deploy cloud function A that will publish messages to the new topic
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "github-func-a"
      - "--runtime=python310"
      - "--trigger-http"
      - "--entry-point=start_script"
      - "--region=europe-west3"
      - "--no-allow-unauthenticated"
      - "--max-instances=1"
      - "--timeout=120s"
      - "--memory=256MiB"
      - "--ingress-settings=all"
      - "--gen2"
      - "--service-account=sa-func-a@propane-nomad-396712.iam.gserviceaccount.com"
      - "--source=./code/publisher"

  # 2. Deploy cloud function B that will subscribe to the new topic
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "functions"
      - "deploy"
      - "github-func-b"
      - "--runtime=python310"
      - "--trigger-topic=github-topic"
      - "--entry-point=pubsub_handler"
      - "--region=europe-west3"
      - "--no-allow-unauthenticated"
      - "--max-instances=1"
      - "--timeout=120s"
      - "--memory=256MiB"
      - "--ingress-settings=all"
      - "--gen2"
      - "--service-account=sa-func-b@propane-nomad-396712.iam.gserviceaccount.com"
      - "--source=./code/subscriber"
